#!/bin/bash

echo killing
## get pid of process
PID=`lsof -i:3000 -t`
kill $PID
echo installing
npm install
echo deploying
screen -d -m npm start >> /var/tmp/deployment_logs.log
echo "consult deployment_log file to see output of deployment"
